name: audio_service_plus
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service_platform_interface: ^0.1.0
  audio_session: ^0.1.6+1
  rxdart: '>=0.26.0 <0.28.0'
  flutter_cache_manager: ^3.0.1
  clock: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.suchone.audio_service_plus
        pluginClass: AudioServicePlusPlugin
      ios:
        pluginClass: AudioServicePlusPlugin